#sudo: false
osx_image: xcode7

language: objective-c

before_install:
  # - gem install cocoapods # -v '0.37.2'
  # - brew update
  - brew outdated xctool || brew upgrade xctool
  # - pod install
  # - xctool --version

# podfile: LogCat/Podfile

branches:
only:
  - master

script:
  - xctool -workspace LogCat/LogCat.xcworkspace -scheme LogCat
